[package]
name = "bitsy-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.0"
async-trait = "0.1"
bincode = "1.3"
bytes = { version = "1.3", features = ["serde"] }
nom = "5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
url = "2.3"
bitsy-macros = { path = "./../bitsy-macros" }