[package]
name = "bitsy-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
lazy_static = "1.4"
proc-macro-error = "1.0"
proc-macro2 = "1.0"
quote = "1"
serde = { version = "1.0", default-features = false, features = ["derive"] }
sha2 = "0.9.5"
syn = { version = "1.0", features = ["full"] }
